FIX: CI runner environment

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -78,9 +78,10 @@ jobs:
         run: |
           docker compose up -d --build
 
-      - name: Configure Shell
+      - name: Configure Environment
         run: |
-          set -o pipefail # make the pipe exist status carry non-zero values
+          set -o pipefail # make the pipe exist status carry non-zero values;
+          echo 'DEBUG=false' > .env
 
       - name: Run Django Tests
         if: always()
