Fix testing environment config

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -76,9 +76,9 @@ jobs:
 
       - name: Configure Environment
         run: |
-          set -o pipefail # make the pipe exist status carry non-zero values;
-          echo 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' > .env
-          echo 'OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}' >> .env
+          set -o pipefail; # make the pipe exist status carry non-zero values;
+          echo 'DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}' > .env;
+          echo 'OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}' >> .env;
 
       - name: Start Containers
         run: |
@@ -97,7 +97,7 @@ jobs:
       - name: Check Coverage >= 80%
         run: |
           chmod +x ./scripts/check-coverage.sh;
-          ./scripts/check-coverage.sh coverage_report.txt # | tee coverage_verdict.txt
+          ./scripts/check-coverage.sh coverage_report.txt | tee coverage_verdict.txt
 
       - name: Create Step Summary
         if: always()
